### ISSUE TITLE
"Issueベースの開発"レビュー依頼

### ISSUE THREAD

**Issue by menma0214** [menma0214/yochiyochi#34]

**Comment by menma0214** [comment]
## 概要

### 実装予定の機能
 - [ ] 施設情報投稿機能
 - [ ] イベント情報投稿機能

**Comment by Tsuchiya2** [comment]
![image](https://github.com/menma0214/graduation_exhibition_original_application/assets/61481161/25a37b88-856a-4f3f-951a-00dacedd5fa8)

projectsにアクセスしましたが、看板・issue・ストーリーポイントが確認できませんでした。
上記確認できる状態でご提出をお願いいたします。

**Comment by menma0214** [comment]
大変失礼致しました。
意図せずにプライベート設定になっておりました。
変更して、再度レビュー依頼させていただきます。

**Comment by Tsuchiya2** [comment]
確認できました。
概ね良いかと思います。LGTMです。
以下のissueはMVP後の実装で良いかと思いますのでご検討ください。

- マイページ
- イベント一覧
- イベント詳細
- お気に入り登録
- お気に入り一覧
- 問い合わせフォーム
- 退会申請

**Comment by menma0214** [comment]
承知しました！
ご確認いただきありがとうございます。
MVP後にご提示いただきましたissueを実装するようにいたします。
