### ISSUE TITLE
MVPリリース

### ISSUE THREAD

**Issue by menma0214** [menma0214/yochiyochi#82]
## 各種情報
サービス名：yochiyochi-よちよち-
サービスURL: https://yochiyochi.onrender.com/tops

## READMEレビュー時にMVPリリース時点で実装予定だった機能
- [ ] 各管理者ページ
- [ ] イベント一覧ページ
- [ ] マイページ
- [ ] 問い合わせフォーム
- [ ] 退会申請フォーム
- [ ] お気に入り機能
- [ ] 会員登録時アンケート機能
- [ ] タグづけ、タグ検索機能（プルダウン）

READMEレビュー時に実装予定だった機能が実装できているかがわかるように記載してください

## READMEレビュー時から変更した機能
 - 本リリース後に一覧画面の各施設、遊具。レビューのパーシャルのデザインを変更する予定です。
 - 画像のアップロード時のサイズ調整を実装予定（画質の崩れを防ぐため）

## サービスイメージがわかるようなスクリーンショット等
特に管理画面など通常ユーザーが触れない機能があったら共有をお願いします
トップ画面：[![Image from Gyazo](https://i.gyazo.com/1a351c4f7760917bcf90aa64de30cb64.jpg)](https://gyazo.com/1a351c4f7760917bcf90aa64de30cb64)
施設詳細画面：[![Image from Gyazo](https://i.gyazo.com/eb775b2bbad979d5f35f91022ac5d244.jpg)](https://gyazo.com/eb775b2bbad979d5f35f91022ac5d244)
レビュー画面：[![Image from Gyazo](https://i.gyazo.com/401be86abdf0809ace0562f601376a05.jpg)](https://gyazo.com/401be86abdf0809ace0562f601376a05)
レビュー投稿：[![Image from Gyazo](https://i.gyazo.com/b8c184a73f25ad5ad931f4fde684dc5a.jpg)](https://gyazo.com/b8c184a73f25ad5ad931f4fde684dc5a)
パスワードリセット受付メール：[![Image from Gyazo](https://i.gyazo.com/2f8b22cbf782550dec5d2e3e0d15ad73.png)](https://gyazo.com/2f8b22cbf782550dec5d2e3e0d15ad73)
パスワード再設定：[![Image from Gyazo](https://i.gyazo.com/151a4f45249ed6650d5231089e0eb2ae.jpg)](https://gyazo.com/151a4f45249ed6650d5231089e0eb2ae)

## 講師の方へ一言
お忙しいところ、恐れ入りますがご確認をお願いします！

**Comment by rdhdchloe** [comment]
ご対応ありがとうございます！
以下コメントになります。

---

スクショーの各機能を確認できました！

下記機能について確認ができませんでした。

1.  パスワードリセット
存在しないメールアドレスを入力しても、`パスワードリセットのメールを送信しました`と表示されます。

2. ファシリティのレビュー
ファシリティがnilの場合500エラーが発生します。
適切なページへの遷移とフラッシュメッセージの対応をお願いします！


もし実装できているのであれば、コメントに確認手順を詳しく記載してください。
上記いずれかのご対応の上、RUNTEQアプリから再提出してください。

**Comment by menma0214** [comment]
## 下記機能修正

---
### 1. パスワードリセット
         - パスワードリセット時に存在しないアドレスを入力した場合のフラッシュメッセージを修正。

### 2. ファシリティのレビュー
         - facilityがnilの際に起こる500エラー対策に三項演算子とif文を追記しリンク先を修正。

**Comment by kenchasonakai** [comment]
LGTMです！
